[repository]
name = "virtual-desktops"
authors = ["LevMyskin"]
commit_pins = [
    # Hyprland v0.34
    ["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "04ebef1386344b835ad4e33edeb8b97c127d9624"],
    ["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "cccba497c820c3735d8bbdf591f1515b74f17924"],
    # Hyprland v0.35
    ["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "c55bcdddcd299f1f7a819193fed62cfa2c64fec7"],
    # Hyprland v0.36
    ["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "423f2b7377cccfd789f8685d1ea1bbc205bb46a0"],
    # Hyprland v0.37
    ["19c90048d65a5660384d2fb865926a366696d6be", "5d04c55fdbaf26c5ee8e01a86b167eaa889dfcfc"],
    # Hyprland v0.37.1
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "5d04c55fdbaf26c5ee8e01a86b167eaa889dfcfc"],
    ["c5e28ebcfe00a510922779b2c568cfa52a317445", "88e5673994bb6fee2d3b5fa409dfcb59faaff527"],
    # Hyprland v0.38.0
    ["3875679755014997776e091ff8903acfb311dd2f", "88e5673994bb6fee2d3b5fa409dfcb59faaff527"],
    # Hyprland v0.38.1
    ["360ede79d124ffdeebbe8401f1ac4bc0dbec2c91", "88e5673994bb6fee2d3b5fa409dfcb59faaff527"],
    # Hyprland v0.39.0
    ["e93fbd7c4f991cb8ef03e433ccc4d43587923e15", "2a90d57bdfdee1a153fd321bc2da0924b8409c3b"],
    # Hyprland v0.39.1
    ["fe7b748eb668136dd0558b7c8279bfcd7ab4d759", "2a90d57bdfdee1a153fd321bc2da0924b8409c3b"],
    # Hyprland v0.40.0
    ["cba1ade848feac44b2eda677503900639581c3f4", "e3bad3b9ab3dac25ad77641a2037601035125535"],
    # Hyprland v0.41.0
    ["ea2501d4556f84d3de86a4ae2f4b22a474555b9f", "e42e505ce82b2ad0d33b56e9e1e600db7ebb9e7a"],
    # Hyprland v0.41.1
    ["9e781040d9067c2711ec2e9f5b47b76ef70762b3", "b5121a450a66382fd8e6e28e93d83430c86043a6"],
    # Hyprland v0.41.2
    ["918d8340afd652b011b937d29d5eea0be08467f5", "8599ce045052b1df2eda37c157938dd5a500b2db"],
    # Hyprland v0.42.0
    ["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "2767053e68d54ae9abdcf23e5f0699e000c62daa"],
    # Hyprland v0.43.0
    ["8eea25c8bc162f9259f2b249cd864c3c8a540fd1", "0f594732b063a90d44df8c5d402d658f27471dfe"],
    # Hyprland v0.44.0
    ["8eea25c8bc162f9259f2b249cd864c3c8a540fd1", "0c7a7e2d569eeed9d6025f3eef4ea0690d90845d"],
    # Hyprland v0.44.1
    ["8eea25c8bc162f9259f2b249cd864c3c8a540fd1", "4520b30d498daca8079365bdb909a8dea38e8d55"],
    # Hyprland v0.45.0
    ["d2a1e19839ff76d920bacce2153d0bf78559af11", "a425fbebe4cf4238e48a42f724ef2208959d66cf"],
    # Hyprland v0.46.2
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "dc24bb6a3402827b19d62d7336c1fb31d9b0ee1a"],
    # Hyprland v0.47.0
    ["04ac46c54357278fc68f0a95d26347ea0db99496", "a895b708d6f2995fa093962c00f2048b24bb6807"],
    # Hyprland v0.47.1
    ["75dff7205f6d2bd437abfb4196f700abee92581a", "1337792e4e1b667967c206d670068d8150c3aedf"],
    # Hyprland v0.47.2
    ["882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff", "a4802d97796ee7484d3b405d52e55ea2aabd51d5"],
    # Hyprland v0.48.0
    ["5ee35f914f921e5696030698e74fb5566a804768", "c1e057a87705a3e6edcc22a739becbab8dd7997d"],
    # Hyprland v0.48.1
    ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "c1e057a87705a3e6edcc22a739becbab8dd7997d"],
    # Hyprland v0.48.1
    ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "2906ce00102e52e386b4a315d8ce2cc4d5ef9fe5"],
    # Hyprland v0.49.0
    ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "1013f5f0beab96ec5ec8876d21d7b9e2caee51b6"],
]


[virtual-desktops]
description = "Virtual desktops"
authors = ["LevMyskin"]
output = "virtual-desktops.so"
build = [
    "make all"
]

